package com.ws.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-03T12:55:12.733+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://cxf.ws.com/", name = "HelloWord")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWord {

    @WebMethod
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://cxf.ws.com/", className = "com.ws.cxf.GetCatsByUser")
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://cxf.ws.com/", className = "com.ws.cxf.GetCatsByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ws.cxf.Cat> getCatsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.cxf.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.ws.com/", className = "com.ws.cxf.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.ws.com/", className = "com.ws.cxf.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
