package com.ws.cxf.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.ws.cxf.HelloWord;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-03T12:55:12.782+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "HelloWordImpl", 
                  wsdlLocation = "http://192.168.198.1:8888//CXF_And_Spring/cxfservice/getCatsByUser?wsdl",
                  targetNamespace = "http://impl.cxf.ws.com/") 
public class HelloWordImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxf.ws.com/", "HelloWordImpl");
    public final static QName HelloWordImplPort = new QName("http://impl.cxf.ws.com/", "HelloWordImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.198.1:8888//CXF_And_Spring/cxfservice/getCatsByUser?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWordImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.198.1:8888//CXF_And_Spring/cxfservice/getCatsByUser?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWordImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWordImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWordImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWordImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWordImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWordImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWord
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public HelloWord getHelloWordImplPort() {
        return super.getPort(HelloWordImplPort, HelloWord.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWord
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public HelloWord getHelloWordImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWordImplPort, HelloWord.class, features);
    }

}
